Add files via upload
Disculpa por usar el método prohibido, intenté hacerlo con la terminal pero me salía este error  "To github.com:enriqueferreruz/ccsAvanzado.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'github.com:enriqueferreruz/ccsAvanzado.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."